
services:
  web:
    container_name: zabbix_morda
    image: zabbix/zabbix-web-nginx-pgsql
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      POSTGRES_DB: zabbix_db
      POSTGRES_USER: zabbixdbuser
      POSTGRES_PASSWORD: 123qwe
      ZBX_SERVER_HOST: zabbix
      ZBX_SERVER_PORT: 10051
      PHP_TZ: Asia/Tomsk
    restart: always
    depends_on:
      - postgres
    ports:
      - "10.122.33.1:80:8080"
    networks:
      zabbix_net:
        ipv4_address: 10.122.33.2

  postgres:
    container_name: zabbix_db
    image: postgres:14
    volumes:
      - ./_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: zabbix_db
      POSTGRES_USER: zabbixdbuser
      POSTGRES_PASSWORD: 123qwe
    restart: always
    networks:
      zabbix_net:
        ipv4_address: 10.122.33.3

  zabbix:
    container_name: zabbix_server
    image: zabbix/zabbix-server-pgsql
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      POSTGRES_DB: zabbix_db
      POSTGRES_USER: zabbixdbuser
      POSTGRES_PASSWORD: 123qwe
      ZBX_VALUECACHESIZE: 64M
      ZBX_CACHESIZE: 128M
      ZBX_TRENDCACHESIZE: 128M
    ports:
      - "10051:10051"
    restart: always
    depends_on:
      - postgres
    networks:
      zabbix_net:
        ipv4_address: 10.122.33.4


networks:
  zabbix_net:
    ipam:
      driver: default
      config:
        - subnet: 10.122.33.0/24

